### ISSUE TITLE
Bug - path name doubles up

### ISSUE THREAD

**Issue by bvellacott** [broccolijs/broccoli-concat#104]
when I did the followong:

```
        var concat = require('broccoli-concat');
        var bundlePath = 'aura/AuraComponent';
        var controllerName = 'AuraComponentController.js'
 	var testableController = concat(bundlePath, {
	  outputFile: controllerName + '.hintable',
	  header: "module.exports = ",
	  inputFiles: [controllerName],
	  footer: ';',
	  sourceMapConfig: { enabled: false },
	  allowNone: true
	});

```
I got the error:

```
Error: ENOENT: no such file or directory, open 'aura/AuraComponent/aura/AuraComponent/AuraComponentController.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Simple.addFile (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli-concat/concat-without-source-maps.js:15:21)
    at Concat.<anonymous> (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli-concat/concat.js:205:17)
    at Array.forEach (native)
    at Concat.addFiles (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli-concat/concat.js:203:9)
    at Concat.<anonymous> (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli-concat/concat.js:138:10)
    at Simple.end (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli-concat/concat-without-source-maps.js:32:17)
    at Concat.build (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli-concat/concat.js:117:22)
    at TransformNodeWrapper.build (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli/lib/builder.js:440:43)
    at /home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/broccoli/lib/builder.js:101:23
    at tryCatch (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/home/benjamin/Desktop/projects/mavensmate/yahoo/resource-bundles/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

In version 3.1.1.

Reverting to version 3.0.5 fixed the issue

**Comment by trentmwillis** [comment]
Thanks for reporting. I'll look into this.

**Comment by trentmwillis** [comment]
@bvellacott any chance you can provide a reproduction of this issue? I'm having trouble recreating it on my end.

**Comment by bvellacott** [comment]
I've moved on, but will give it a try
