### ISSUE TITLE
Bug Concat: Result is empty and allowNone is falsy.

### ISSUE THREAD

**Issue by pohodnya** [broccolijs/broccoli-concat#106]
Build failed.
The Broccoli Plugin: [SimpleConcatConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
Error: Concat: Result is empty and allowNone is falsy.

package.json:
```coffee
{
  "name": "crm",
  "version": "0.1.0",
  "description": "CRM application",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 4.5.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "active-model-adapter": "~2.1.1",
    "broccoli-asset-rev": "^2.5.0",
    "broccoli-clean-css": "^1.1.0",
    "ember-ajax": "~2.5.4",
    "ember-cli": "~2.10.1",
    "ember-cli-app-version": "^1.0.1",
    "ember-cli-babel": "~5.1.10",
    "ember-cli-chai": "~0.3.2",
    "ember-cli-coffeescript": "~1.15.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-emblem": "~0.8.1",
    "ember-cli-flash": "1.4.1",
    "ember-cli-foundation-6-sass": "0.0.16",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.6.1",
    "ember-cli-jshint": "^1.0.5",
    "ember-cli-mirage": "0.2.5",
    "ember-cli-mocha": "~0.13.2",
    "ember-cli-mocha-coffeescript": "git+https://github.com/mhluska/ember-cli-mocha-coffeescript.git",
    "ember-cli-moment-shim": "~2.2.1",
    "ember-cli-numeral": "0.2.0",
    "ember-cli-rails-addon": "~0.8.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sass": "5.6.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-test-loader": "^1.1.1",
    "ember-cli-uglify": "^1.2.0",
    "ember-cli-version-checker": "^1.1.6",
    "ember-data": "~2.10.0",
    "ember-export-application-global": "^1.1.1",
    "ember-font-awesome": "3.0.3",
    "ember-load-initializers": "^0.5.1",
    "ember-moment": "7.3.0",
    "ember-power-select": "1.4.3",
    "ember-power-select-with-fallback": "https://github.com/pohodnya/ember-power-select-with-fallback.git",
    "ember-resolver": "^2.1.1",
    "ember-simple-auth": "~1.2.0",
    "ember-welcome-page": "^1.0.4",
    "loader.js": "^4.1.0",
    "rsvp": "^3.3.3"
  },
  "ember-addon": {
    "paths": [
      "../-shared"
    ]
  }
}
```
bower.json:
```coffee
{
  "name": "crm",
  "dependencies": {
    "ember": "~2.10.2",
    "ember-cli-shims": "~0.1.3",
    "foundation-sites": "~6.2.4",
    "moment": "^2.17.1",
    "font-awesome": "~4.7.0"
  }
}
```
ember-cli-build.js:
```javascript
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    babel: {
      includePolyfill: true
    },

    fingerprint: {
      prepend: '/crm/',
      extensions: ['js', 'css', 'png', 'gif', 'jpeg', 'jpg', 'svg', 'eot', 'ttf', 'woff']
    },

    'ember-font-awesome': {
      fontsOutput: "/fonts/",
      useScss: true
    },

    'ember-cli-foundation-6-sass': {
      'foundationJs': 'all'
    }
  });

  app.import('bower_components/moment/locale/ru.js');

  return app.toTree();
};
```
full error:
```
Error: Concat: Result is empty and allowNone is falsy.
  at Concat._doPatchBasedBuild (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:143:11)
  at Concat.build (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:104:17)
  at /home/aleksey/projects/ta/frontend/crm/node_modules/broccoli-plugin/read_compat.js:93:34
  at tryCatch (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:553:13)
  at publish (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:521:7)
  at flush (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:2373:5)
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickCallback (node.js:365:13)


The broccoli plugin was instantiated at: 
  at Concat.Plugin (/home/aleksey/projects/ta/frontend/crm/node_modules/broccoli-plugin/index.js:7:31)
  at new Concat (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:38:10)
  at module.exports (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
  at EmberApp.concatFiles (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/broccoli/ember-app.js:369:10)
  at EmberApp._concatFiles (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/broccoli/ember-app.js:382:15)
  at EmberApp.styles (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/broccoli/ember-app.js:1334:28)
  at EmberApp.toArray (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/broccoli/ember-app.js:1647:10)
  at EmberApp.toTree (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/broccoli/ember-app.js:1668:30)
  at module.exports (/home/aleksey/projects/ta/frontend/crm/ember-cli-build.js:41:14)
  at CoreObject.module.exports.Task.extend.setupBroccoliBuilder (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/models/builder.js:72:19)
  at CoreObject.module.exports.Task.extend.init (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/models/builder.js:52:10)
  at CoreObject.superWrapper [as init] (/home/aleksey/projects/ta/frontend/crm/node_modules/core-object/lib/assign-properties.js:32:18)
  at CoreObject.Class (/home/aleksey/projects/ta/frontend/crm/node_modules/core-object/core-object.js:32:33)
  at CoreObject.module.exports.Task.extend.run (/home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/tasks/build.js:15:19)
  at /home/aleksey/projects/ta/frontend/crm/node_modules/ember-cli/lib/commands/build.js:32:24
  at tryCatch (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:553:13)
  at /home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:628:16
  at flush (/home/aleksey/projects/ta/frontend/crm/node_modules/rsvp/dist/rsvp.js:2373:5)
  at nextTickCallbackWith0Args (node.js:436:9)
  at process._tickCallback (node.js:365:13)
```

**Comment by trentmwillis** [comment]
Was your `vendor.css` file empty previously after build?

I think I may have missed an edge case in the recent refactor. Previously, we only threw on `allowNone: false` when _no input files were found_. Now, due to being patch-based, we throw when _the concatenation result is empty_. Theoretically, as I believe is happening here, you can have _a concatenation result which is empty **but** has input files_.

**Comment by pohodnya** [comment]
@trentmwillis Yes `vendor.css` file is empty after build when using `broccoli-concat: "~3.1.1"`

**Comment by cibernox** [comment]
I confirm I'm seeying the same problem, and it's related with 3.2.0. v3.1.1 worked ok.
Yarn will save me from this.

**Comment by rwjblue** [comment]
I released the code from v3.1.1 as v3.2.1 to clear any issues for folks while we get it fixed properly.

**Comment by Turbo87** [comment]
I guess https://github.com/ember-cli/ember-cli-mocha/issues/172 is related to this as well

**Comment by jessepollak** [comment]
We ran into this as well - thank you for the quick rollback!

**Comment by trentmwillis** [comment]
Just opened a PR to fix: https://github.com/broccolijs/broccoli-concat/pull/107

**Comment by pixelhandler** [comment]
I'm working on an addon for test helpers with @cibernox and we have no CSS in the addon. Build was working. Then I added some CSS and the build broke. I removed the CSS and the build still broke.

```
Build failed.
The Broccoli Plugin: [SimpleConcatConcat: Concat: Vendor Styles/assets/vendor.css] failed with:
Error: Concat: Result is empty and allowNone is falsy.
```

Build: https://travis-ci.org/cibernox/ember-native-dom-helpers/jobs/204359404
PR builds: https://travis-ci.org/cibernox/ember-native-dom-helpers/pull_requests - history in `PR #2`

@rwjblue is there a work around? Looks like yarn lock is on 3.2.0 see https://github.com/cibernox/ember-native-dom-helpers/blob/master/yarn.lock#L581-L596

**Comment by rwjblue** [comment]
@pixelhandler - The fix is released, you need to do `yarn upgrade broccoli-concat` to get it.
