### ISSUE TITLE
[fixed] Error: ENOENT: no such file or directory (issue with 3.5.1)

### ISSUE THREAD

**Issue by stefanpenner** [broccolijs/broccoli-concat#130]
```
ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
=================================================================================
ENV Summary:
  TIME: Wed Jul 25 2018 14:38:29 GMT+0000 (UTC)
  TITLE: ember
  ARGV:
  - /home/travis/.nvm/versions/node/v8.11.3/bin/node
  - /home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/ember-cli/bin/ember
  - test
  EXEC_PATH: /home/travis/.nvm/versions/node/v8.11.3/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/travis/.yarn/bin
  - /home/travis/.rvm/gems/ruby-2.4.1/bin
  - /home/travis/.rvm/gems/ruby-2.4.1@global/bin
  - /home/travis/.rvm/rubies/ruby-2.4.1/bin
  - /home/travis/.rvm/bin
  - ./node_modules/.bin
  - /home/travis/bin
  - /home/travis/.local/bin
  - /opt/pyenv/shims
  - /home/travis/.phpenv/shims
  - /home/travis/perl5/perlbrew/bin
  - /home/travis/.nvm/versions/node/v8.11.3/bin
  - /home/travis/.kiex/elixirs/elixir-1.4.5/bin
  - /home/travis/.kiex/bin
  - /home/travis/gopath/bin
  - /usr/local/phantomjs/bin
  - /usr/local/phantomjs
  - /usr/local/neo4j-3.2.7/bin
  - /usr/local/maven-3.5.2/bin
  - /usr/local/cmake-3.9.2/bin
  - /usr/local/clang-5.0.0/bin
  - /home/travis/.gimme/versions/go1.7.4.linux.amd64/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /home/travis/.phpenv/bin
  - /opt/pyenv/bin
  - /home/travis/.yarn/bin
  PLATFORM: linux x64
  FREEMEM: 29225865216
  TOTALMEM: 67275345920
  UPTIME: 499
  LOADAVG: 31.50341796875,24.88134765625,11.72412109375
  CPUS:
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  - AMD EPYC 7401P 24-Core Processor - 1996
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.3
  - openssl: 1.0.2o
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11
ERROR Summary:
  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Entry.get content [as content] (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/lib/strategies/simple.js:25:22)
    at contentMapper (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/lib/strategies/simple.js:7:16)
    at Array.map (<anonymous>)
    at SimpleConcat.result (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/lib/strategies/simple.js:158:22)
    at Concat._doPatchBasedBuild (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/concat.js:140:31)
    at Concat.build (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/concat.js:102:19)
    at /home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  - codeFrame: ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `SimpleConcatConcat` plugin. 💥
ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Build Canceled: Broccoli Builder ran into an error with `SimpleConcatConcat` plugin. 💥
ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
  - name: Error
  - nodeAnnotation: SimpleConcatConcat
  - nodeName: SimpleConcatConcat
  - originalErrorMessage: ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
  - stack: Error: ENOENT: no such file or directory, open '[broccoli-persistent-filter:EslintValidationFilter]/addon/engine.lint-test.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Entry.get content [as content] (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/lib/strategies/simple.js:25:22)
    at contentMapper (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/lib/strategies/simple.js:7:16)
    at Array.map (<anonymous>)
    at SimpleConcat.result (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/lib/strategies/simple.js:158:22)
    at Concat._doPatchBasedBuild (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/concat.js:140:31)
    at Concat.build (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-concat/concat.js:102:19)
    at /home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/travis/build/sass-eyeglass/ember-cli-eyeglass/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
=================================================================================
```

**Comment by stefanpenner** [comment]
potentially caused by: https://github.com/broccolijs/broccoli-concat/pull/128 
Investigating now

**Comment by scottkidder** [comment]
Thanks @stefanpenner Greatly appreciated!
